#numpy is useful for handling n dimenssinal 
#array, arrays are homogeneous

#OPERATIONS OF NESTED LISTS BECOMES DIFFICULT TO PROCESS WITHOUT NUMPY

#if we name file as numpy.py it will import our own file in our code when we say import numpy
import numpy as np
#create 1D array

a=np.array([12,13,23,45])    #Converts list into Numpy Array
print(a)
#the type of a
print("array type ",type(a))
#the type of data in the array
print("data type",a.dtype)
print("Dimensions: ",a.ndim) #find dimenssions
#to find number of rows and columns
print("shape :",a.shape)   #tuple of size 1

a=np.array([["xxx","yyy"],["zzz","pppp"]])
print(a)
print("array type ",type(a))
print("data type",a.dtype)
print("Dimensions: ",a.ndim) #find dimenssions
print("shape :",a.shape)

#create 2d array
import numpy as np
a=np.array([[12,13,23.78,45],[45,22,45,55]])
print(a)
print("array type ",type(a))
print("data type",a.dtype)
print("Dimensions: ",a.ndim) #find dimenssions
print("shape :",a.shape)

#create 3D array

s=np.array([[[1,2,3],[10,20,30]],[[5,6,7],[8,9,10]]])
print(s)
print("array type ",type(s))
print("data type",s.dtype)
print("Dimensions: ",s.ndim) #find dimenssions
print("shape :",s.shape)

#add 0 to 11 in array b
b=np.arange(12)
print(b)
c=np.arange(1,32,2).reshape(4,4) # both the number of elements and the no. of numbers generated by arange should match, otherwise error
print(c)
print(c[1:3,2:4]) # slices matrix to retrieve rows from 1 to 2 and column 2 to 3
print(c[1:4,1])
print(c[1:2,3])
print(c[1,-1]) # first rows'last column value

#to arrange data columnwise
c=np.arange(1,32,2).reshape(4,4,order='f')
print(c)

c[2,1]=231

a=np.zeros((3,3),dtype='int32')
b=np.ones((3,3))
c=np.empty((3,3)) #to create array of unknown values
print(a)
print()
print(b)
print()
print(c)
print()

#memberwise addition
a=a+b
print(a)
print()
a=a+10
print(a)
print()
#memberwise multiplication
print(a*b)
print()
#matrix multiplication
print(a.dot(b))
print()

#identity matrix
a=np.identity(3)
print(a)
print()
#matrix multiplication
b=np.arange(9).reshape(3, 3)
b=b+10
print(a.dot(b))
print()
b=np.eye(3,4)
print(b)
print()
b=np.eye(4,5,k=1)
print(b)
print()

#filter the array

a=np.array([[12,13,14,15],[3,24,13,6],[10,18,1,2]])
print(a)
print(a[a%6==0])
print(a[a>5])

#to search the value
print(np.where(a%2==0))
print(list(np.where(a%2==0)[0].data))

#to find sum of all values
print(np.sum(a,axis=1)) # row wise sum
print(np.sum(a,axis=0)) # column wise sum
print(np.sum(a)) # sum of all values

#to find mean
print(np.mean(a))
print(np.mean(a,axis=1))

#hstack and vstack
x=np.array([10,20,30])
y=np.array([11,12,13])
z=np.array([21,22,23])

#to arrange data horizontally
print(np.hstack((x,y,z)))

d=np.vstack((x,y,z))
print(np.vstack((x,y,z)))

#revesrse columns and rows both
print(np.flip(d))
#flips the rows, the 1st row will be the last row
#last row will be the first row
print(np.flip(d,axis=1)) 

#endpoint=False will exclude 30
x=np.linspace(10,30,7,endpoint=False) #Generate 7 equidistant points between 10 and 30, excluding 10 and 30.
print(x)
x=np.linspace(10,30,7,endpoint=True) #Generate 7 equidistant points between 10 and 30, including 10 and 30.
print(x)

import numpy as np
student=np.array([[40,50,48],[30,35,38],[44,38,48]])
print(student)
avmks=np.mean(student,axis=1)
print(avmks)
names=['student1','student2','student3']
import matplotlib.pyplot as plt
plt.pie(avmks,labels=names)
plt.bar(names,avmks)



